twig:
    file_name_pattern: '*.twig'
    debug: '%kernel.debug%'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]

when@test:
    twig:
        strict_variables: false
        debug: '%kernel.debug%'
