version: '3.8'

services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    restart: always  
    container_name: php-fpm
    volumes:
      - ./../:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=localhost
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METOD: true
    ports:
      - "5432:5432"
    labels:
      - "com.symfony.server.service-prefix=DATABASE"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9090:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge 
    
volumes:
  pg_data:
  pgadmin_data:
